[package]
name = "tiny-md-compiler"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "tmdc"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"