name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo test --verbose

  build-macos:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo test --verbose

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo test --verbose
