name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: cargo test --verbose linux
        run: cargo test --verbose

  tests-macos:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: cargo test --verbose macos
        run: cargo test --verbose

  tests-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: cargo test --verbose windows
        run: cargo test --verbose
